public class Main {
    public static void main(String[] args) {
        byte a = 1;
        short b = 300;
        int c = 800;
        long d = 2345677232434L;
        float e = 8.6f;
        double f = 10.3;
        System.out.println("Значение переменной a с типом bute равно " + a);
        System.out.println("Значение переменной b с типом short равно " + b);
        System.out.println("Значение переменной c с типом int равно " + c);
        System.out.println("Значение переменной d с типом long равно " + d);
        System.out.println("Значение переменной e с типом float равно " + e);
        System.out.println("Значение переменной f с типом double равно " + f);
        float q = 27.12f;
        long z = 987678965549L;
        float m = 2.786f;
        short h = 569;
        short k = -159;
        int l = 27897;
        byte r = 67;
        System.out.println(q);
        System.out.println(z);
        System.out.println(m);
        System.out.println(h);
        System.out.println(k);
        System.out.println(l);
        System.out.println(r);
        byte lp = 23;
        byte as = 27;
        byte ea = 30;
        short sheets = 480;
        int ed = lp + as + ea;
        int lisB = sheets / ed;
        System.out.println("На каждого ученика рассчитано " + lisB + " листов бумаги");
        byte performance = 16;
        byte time = 2;
        int minP = performance / time;
        System.out.println("За минуту машина произвела " + minP + " штук бутылок");
        byte j = 8;
        byte n = 20;
        int prMin = j * n;
        System.out.println("За " + n + " минут машина произвела " + prMin + " штук бутылок");
        byte t = 8;
        short g = 60;
        int kl = 24;
        int sutKi = t * g * kl;
        System.out.println("За сутки машина произвела " + sutKi + " штук бутылок");
        byte i = 8;
        short u = 60;
        int y = 72;
        int treD = i * u * y;
        System.out.println("За 3 дня машина произвела " + treD + " штук бутылок");
        byte v = 8;
        byte x = 60;
        short we = 720;
        int mes = v * x * we;
        System.out.println("За месяц машина произвела " + mes + " штук бутылок");
        byte ba = 120;
        short wait = 2;
        short brown = 4;
        int rf = wait + brown;
        int cla = ba / rf;
        int bel = cla * 2;
        int kor = cla * 4;
        System.out.println("В школе, где " + cla + " классов, нужно " + bel + " банок белой краски и " + kor + " банок коричневой краски");
        byte ban = 5;
        short weq = 80;
        int qwe = ban * weq;
        short milk = 200;
        byte on = 105;
        short nad = 100;
        int sd = milk / nad * on;
        byte ice = 100;
        short xc = 2;
        int cre = ice * xc;
        byte egg = 4;
        short wes = 70;
        int egf = egg * wes;
        int res = qwe + sd + cre + egf;
        double obe = res / 1000.0;
        System.out.println(res + " гр или " + obe + " кг!");
        int sbr = 7000;
        short po = 250;
        short pt = 500;
        int cv = sbr / po;
        int bn = sbr / pt;
        int gh = po + pt;
        double ff = gh / 2.0;
        double ww = sbr / ff;
        System.out.println("Если спортсмен будет терять каждый день по 250 грамм уйдет " + cv + " дней");
        System.out.println("Если каждый день будет худеть на 500 грамм уйдет " + bn + " дней");
        System.out.println("Может потребоваться " + ww + " дней в среднем, чтобы добиться результата похудения.");
        int ma = 67760;
        float dfg = ma * 0.10f;
        float pol = ma + dfg;
        float cxz = dfg * 12;
        System.out.println("Маша теперь получает " + pol + " рублей. Годовой доход вырос на " + cxz + " рублей");
        int den = 83690;
        float rtf = den * 0.10f;
        float vir = den + rtf;
        float ghy = rtf * 12;
        System.out.println("Денис теперь получает " + vir + " рублей. Годовой доход вырос на " + ghy + " рублей");
        int kri = 76230;
        float kik = kri * 0.10f;
        float kkk = kri + kik;
        float kye = kik * 12;
        System.out.println("Кристина теперь получает " + kkk + " рублей. Годовой доход вырос на " + kye + " рублей");
    }
}