public class Main {
    public static void main(String[] args) {
        Byte a = 1;
        Short b = 300;
        int c = 800;
        Long d = 2345677232434L;
        Float e = 8.6f;
        Double f = 10.3;
        System.out.println("Значение переменной a с типом Bute равно " + a);
        System.out.println("Значение переменной b с типом Short равно " + b);
        System.out.println("Значение переменной c с типом int равно " + c);
        System.out.println("Значение переменной d с типом Long равно " + d);
        System.out.println("Значение переменной e с типом Float равно " + e);
        System.out.println("Значение переменной f с типом Double равно " + f);
        Float q = 27.12f;
        Long z = 987678965549L;
        Float m = 2.786f;
        Short h = 569;
        Short k = -159;
        int l = 27897;
        Byte r = 67;
        System.out.println(q);
        System.out.println(z);
        System.out.println(m);
        System.out.println(h);
        System.out.println(k);
        System.out.println(l);
        System.out.println(r);
        Byte lp = 23;
        Byte as = 27;
        Byte ea = 30;
        Short sheets = 480;
        int ed = lp + as + ea;
        int zx = sheets / ed;
        System.out.println("На каждого ученика рассчитано " + zx + " листов бумаги");
        Byte performance = 16;
        Byte time = 2;
        int o = performance / time;
        System.out.println("За минуту машина произвела " + o + " штук бутылок");
        Byte j = 8;
        Byte n = 20;
        int p = j * n;
        System.out.println("За " + n + " минут машина произвела " + p + " штук бутылок");
        Byte t = 8;
        Short g = 60;
        int kl = 24;
        int s = t * g * kl;
        System.out.println("За сутки машина произвела " + s + " штук бутылок");
        Byte i = 8;
        Short u = 60;
        int y = 72;
        int qw = i * u * y;
        System.out.println("За 3 дня машина произвела " + qw + " штук бутылок");
        Byte sa = 8;
        Byte xz = 60;
        Short we = 720;
        System.out.println("За месяц машина произвела " + we + " штук бутылок");
        Byte ba = 120;
        Short wait = 2;
        Short brown = 4;
        int rf = wait + brown;
        int cla = ba / rf;
        int bel = cla * 2;
        int kor = cla * 4;
        System.out.println("В школе, где " + cla + " классов, нужно " + bel + " банок белой краски и " + kor + " банок коричневой краски");
        Byte ban = 5;
        Short weq = 80;
        int qwe = ban * weq;
        short milk = 200;
        Byte on = 105;
        Short nad = 100;
        int sd = milk / nad * 105;
        Byte ice = 100;
        Short xc = 2;
        int cre = ice * xc;
        Byte egg = 4;
        Short wes = 70;
        int egf = egg * wes;
        int res = qwe + sd + cre + egf;
        Double obe = res / 1000.0;
        System.out.println(res + " гр или " + obe + " кг!");
        int sbr = 7000;
        Short po = 250;
        Short pt = 500;
        int cv = sbr / po;
        int bn = sbr / pt;
        int gh = po + pt;
        float ff = gh / 2;
        float ww = sbr / ff;
        System.out.println("Если спортсмен будет терять каждый день по 250 грамм уйдет " + cv + " дней");
        System.out.println("Если каждый день будет худеть на 500 грамм уйдет " + bn + " дней");
        System.out.println("Может потребоваться " + ww + " дней в среднем, чтобы добиться результата похудения.");
        int ma = 67760;
        float dfg = ma * 0.10f;
        float pol = ma + dfg;
        float cxz = dfg * 12;
        System.out.println("Маша теперь получает " + pol + " рублей. Годовой доход вырос на " + cxz + " рублей");
        int den = 83690;
        float rtf = den * 0.10f;
        float vir = den + rtf;
        float ghy = rtf * 12;
        System.out.println("Денис теперь получает " + vir + " рублей. Годовой доход вырос на " + ghy + " рублей");
        int kri = 76230;
        float kik = kri * 0.10f;
        float kkk = kri + kik;
        float kye = kik * 12;
        System.out.println("Кристина теперь получает " + kkk + " рублей. Годовой доход вырос на " + kye + " рублей");
        }
}